apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: dev
gke:
  cluster: projects/resonant-triode-408814/locations/us-west1/clusters/helm-cd-testing-dev
